on:
    push
jobs:
    image-builder:
        name: Build docker
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout current repo
                uses: actions/checkout@v1.1
            -
                name: Use the provided Dockerfile to build an image
                run: docker build -t project13:v1 -f Dockerfile .
    image-runner:
        name: Run the image
        runs-on: self-hosted
        needs: image-builder
        steps:
            -
                name: Run the image
                run: docker run project13:v1
    test:
        name: Testing
        runs-on: self-hosted
        needs: image-runner
        steps:
            -
                name: Test the code
                run: ./test.sh
